title: Annie are you okay?
description: Generation X dads discuss schooling, parenting, and futures
author: Vikas Jhunjhunwala
email: vikas@sunshine-schools.com
lang: en-us
copyright: "&#x2117; 2024"
logo: /assets/img/logo.png
# baseurl: "/give-generously-intl"
# url: "https://www.sunshineschool.in/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
